import crypto from 'node:crypto';
import fs from 'node:fs';
import fsp from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import process from 'node:process';
import {spawn} from 'node:child_process';
import {inflateRawSync} from 'node:zlib';
const repoRoot=path.resolve(import.meta.dirname,'..'),artifactRoot=path.join(repoRoot,'artifacts'),evidenceRoot=path.join(repoRoot,'verification','evidence');
const attachments=['输入数据包.zip','reference.zip','关键标准答案.xlsx','任务规格转化.xlsx'];
const expectedReference=['output/reports/cuped_revenue_by_variant.csv','output/reports/data_quality_flags.csv','output/reports/randomization_balance.csv','output/sql/analyze_checkout_experiment.sql'].sort();
const assert=(value,message)=>{if(!value)throw new Error(message);};
const sha256=bytes=>crypto.createHash('sha256').update(bytes).digest('hex'),sha256File=file=>sha256(fs.readFileSync(file));
function zipEntries(file){const data=fs.readFileSync(file);let eocd=-1;for(let index=data.length-22;index>=Math.max(0,data.length-65557);index--){if(data.readUInt32LE(index)===0x06054b50){eocd=index;break;}}assert(eocd>=0,`找不到ZIP目录:${file}`);const count=data.readUInt16LE(eocd+10);let offset=data.readUInt32LE(eocd+16);const entries=new Map();for(let i=0;i<count;i++){assert(data.readUInt32LE(offset)===0x02014b50,`ZIP目录损坏:${file}`);const method=data.readUInt16LE(offset+10),compressedSize=data.readUInt32LE(offset+20),uncompressedSize=data.readUInt32LE(offset+24),nameLength=data.readUInt16LE(offset+28),extraLength=data.readUInt16LE(offset+30),commentLength=data.readUInt16LE(offset+32),localOffset=data.readUInt32LE(offset+42),name=data.subarray(offset+46,offset+46+nameLength).toString('utf8').replaceAll('\\','/'),localNameLength=data.readUInt16LE(localOffset+26),localExtraLength=data.readUInt16LE(localOffset+28),start=localOffset+30+localNameLength+localExtraLength;if(!name.endsWith('/')){const compressed=data.subarray(start,start+compressedSize),body=method===0?compressed:method===8?inflateRawSync(compressed):null;assert(body&&body.length===uncompressedSize,`无法解压${name}`);entries.set(name,body);}offset+=46+nameLength+extraLength+commentLength;}return entries;}
async function extract(file,destination){for(const[name,bytes]of zipEntries(file)){const target=path.resolve(destination,...name.split('/'));assert(target.startsWith(`${path.resolve(destination)}${path.sep}`),`非法ZIP路径:${name}`);await fsp.mkdir(path.dirname(target),{recursive:true});await fsp.writeFile(target,bytes);}}
function workbookSheets(file){const xml=zipEntries(file).get('xl/workbook.xml')?.toString('utf8')??'';return[...xml.matchAll(/<(?:[A-Za-z]+:)?sheet[^>]+name="([^"]+)"/gu)].map(match=>match[1]);}
async function run(command,args,cwd,env={}){const started=Date.now();return await new Promise(resolve=>{let child;try{child=spawn(command,args,{cwd,env:{...process.env,...env},windowsHide:true});}catch(error){resolve({code:1,stdout:'',stderr:error.stack??error.message,elapsed_ms:Date.now()-started});return;}let stdout='',stderr='',settled=false;child.stdout.on('data',chunk=>stdout+=chunk);child.stderr.on('data',chunk=>stderr+=chunk);child.on('error',error=>{if(!settled){settled=true;resolve({code:1,stdout,stderr:`${stderr}${error.stack??error.message}`,elapsed_ms:Date.now()-started});}});child.on('exit',code=>{if(!settled){settled=true;resolve({code:code??1,stdout,stderr,elapsed_ms:Date.now()-started});}});});}
function parseCsv(text){const rows=[];let row=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const char=text[i];if(quoted){if(char==='"'&&text[i+1]==='"'){cell+='"';i++;}else if(char==='"')quoted=false;else cell+=char;}else if(char==='"')quoted=true;else if(char===','){row.push(cell);cell='';}else if(char==='\n'){row.push(cell.replace(/\r$/u,''));rows.push(row);row=[];cell='';}else cell+=char;}if(cell||row.length){row.push(cell.replace(/\r$/u,''));rows.push(row);}const headers=rows.shift()??[];return rows.filter(values=>values.some(value=>value!=='')).map(values=>Object.fromEntries(headers.map((header,index)=>[header,values[index]??''])));}
function files(root){const out=[];function walk(current,prefix=''){if(!fs.existsSync(current))return;for(const entry of fs.readdirSync(current,{withFileTypes:true}).toSorted((a,b)=>a.name.localeCompare(b.name,'en'))){const relative=prefix?`${prefix}/${entry.name}`:entry.name;if(entry.isDirectory())walk(path.join(current,entry.name),relative);else out.push(relative);}}walk(root);return out.sort();}
function treeDigest(root){const lines=[];function walk(current,prefix=''){for(const entry of fs.readdirSync(current,{withFileTypes:true}).toSorted((a,b)=>a.name.localeCompare(b.name,'en'))){const relative=prefix?`${prefix}/${entry.name}`:entry.name,full=path.join(current,entry.name);if(entry.isDirectory())walk(full,relative);else lines.push(`${relative}\0${sha256File(full)}`);}}walk(root);return sha256(Buffer.from(lines.join('\n')));}
function classify(name,bytes){const lower=name.toLowerCase();if(bytes.length>=4&&bytes[0]===0x7f&&bytes.subarray(1,4).toString('ascii')==='ELF')return'linux_elf';if(/\.(?:sh|bash|so)(?:\.|$)/u.test(lower))return'posix_member';if(/^#!.*(?:ba|z|k)?sh/mu.test(bytes.subarray(0,160).toString('utf8')))return'posix_shebang';return null;}
async function prepare(label,mutate){const root=path.join(os.tmpdir(),label);await fsp.rm(root,{recursive:true,force:true});await fsp.mkdir(root,{recursive:true});await extract(path.join(artifactRoot,'输入数据包.zip'),root);const inputRoot=path.join(root,'input_data'),reference=zipEntries(path.join(artifactRoot,'reference.zip'));await fsp.writeFile(path.join(inputRoot,'starter','analyze_checkout_experiment.sql'),reference.get('output/sql/analyze_checkout_experiment.sql'));if(mutate)await mutate(inputRoot);return{root,inputRoot,outputRoot:path.join(root,'output'),reference};}
async function execute(room){return await run('node',['tools/run-task.mjs'],room.inputRoot,{ALE_PG_URL:process.env.ALE_PG_URL});}
function semanticOutput(outputRoot,reference){const actual=files(outputRoot).map(name=>`output/${name}`);assert(JSON.stringify(actual)===JSON.stringify(expectedReference),`输出成员错误:${actual.join(',')}`);const semantic=crypto.createHash('sha256');for(const name of['randomization_balance.csv','cuped_revenue_by_variant.csv','data_quality_flags.csv']){const actualRows=parseCsv(fs.readFileSync(path.join(outputRoot,'reports',name),'utf8')),expectedRows=parseCsv(reference.get(`output/reports/${name}`).toString('utf8'));assert(JSON.stringify(actualRows)===JSON.stringify(expectedRows),`${name}业务字段不一致`);semantic.update(JSON.stringify(actualRows));}const actualSql=fs.readFileSync(path.join(outputRoot,'sql','analyze_checkout_experiment.sql'),'utf8').replaceAll('\r\n','\n'),expectedSql=reference.get('output/sql/analyze_checkout_experiment.sql').toString('utf8').replaceAll('\r\n','\n');assert(actualSql===expectedSql,'完成SQL不一致');semantic.update(actualSql);return semantic.digest('hex');}
await fsp.rm(evidenceRoot,{recursive:true,force:true});await fsp.mkdir(evidenceRoot,{recursive:true});assert(process.platform==='win32'&&process.env.GITHUB_ACTIONS==='true','只接受GitHub托管Windows运行');assert(process.env.ALE_PG_URL,'缺少ALE_PG_URL');const psql=process.env.PSQL_PATH||'psql.exe',version=await run(psql,[process.env.ALE_PG_URL,'-Atc','SHOW server_version_num'],repoRoot);assert(version.code===0&&/^17\d{4}$/u.test(version.stdout.trim()),`需要PostgreSQL17:${version.stderr||version.stdout}`);
const attachmentSha256=Object.fromEntries(attachments.map(name=>[name,sha256File(path.join(artifactRoot,name))])),inputMembers=zipEntries(path.join(artifactRoot,'输入数据包.zip')),scan=[...inputMembers].map(([name,bytes])=>({name,classification:classify(name,bytes)})).filter(item=>item.classification);assert(scan.length===0,`输入含平台专用成员:${JSON.stringify(scan)}`);assert(JSON.stringify([...zipEntries(path.join(artifactRoot,'reference.zip')).keys()].sort())===JSON.stringify(expectedReference),'Reference成员错误');assert(JSON.stringify(workbookSheets(path.join(artifactRoot,'关键标准答案.xlsx')))===JSON.stringify(['交付物答案清单','固定字段答案','固定集合答案','固定数值答案','允许变体答案']),'标答Sheet错误');assert(JSON.stringify(workbookSheets(path.join(artifactRoot,'任务规格转化.xlsx')))===JSON.stringify(['任务规格转化']),'规格Sheet错误');
const cleanRuns=[];for(const label of['Q10542 第一次 中文 空目录','Q10542 第二次 中文 空格目录']){const room=await prepare(label),before=treeDigest(room.inputRoot),result=await execute(room);assert(result.code===0,`${label}入口失败\n${result.stdout}\n${result.stderr}`);const after=treeDigest(room.inputRoot);assert(before===after,`${label}修改输入`);const semantic=semanticOutput(room.outputRoot,room.reference);cleanRuns.push({directory_label:label,exit_code:result.code,input_digest_before:before,input_digest_after:after,semantic_digest:semantic,elapsed_ms:result.elapsed_ms,reference_match:true});}assert(cleanRuns[0].semantic_digest===cleanRuns[1].semantic_digest,'两个目录结果不同');
const crlf=await prepare('Q10542 CRLF',async inputRoot=>{const file=path.join(inputRoot,'starter','analyze_checkout_experiment.sql');const value=await fsp.readFile(file,'utf8');await fsp.writeFile(file,value.replace(/\r?\n/gu,'\r\n'));});let result=await execute(crlf);assert(result.code===0,`CRLF入口失败\n${result.stdout}\n${result.stderr}`);const crlfDigest=semanticOutput(crlf.outputRoot,crlf.reference);assert(crlfDigest===cleanRuns[0].semantic_digest,'CRLF改变业务结果');
const mutation=await prepare('Q10542 阈值变化',async inputRoot=>{const file=path.join(inputRoot,'rules','analysis_policy.sql');const value=await fsp.readFile(file,'utf8');await fsp.writeFile(file,value.replace("'2026-07-10T00:00:00Z','2026-07-17T00:00:00Z',0.4,1","'2026-07-10T00:00:00Z','2026-07-17T00:00:00Z',0.4,0"));});result=await execute(mutation);assert(result.code===0,`阈值变化失败\n${result.stdout}\n${result.stderr}`);const changed=parseCsv(fs.readFileSync(path.join(mutation.outputRoot,'reports','randomization_balance.csv'),'utf8'));assert(changed.filter(row=>row.status==='investigate').length===2,'平衡阈值变化未改变状态');assert(JSON.stringify(changed)!==JSON.stringify(parseCsv(zipEntries(path.join(artifactRoot,'reference.zip')).get('output/reports/randomization_balance.csv').toString('utf8'))),'规则变化未改变报告');
const negative=await prepare('Q10542 缺少口径',async inputRoot=>{await fsp.rename(path.join(inputRoot,'rules','analysis_policy.sql'),path.join(inputRoot,'rules','analysis_policy.sql.missing'));});result=await execute(negative);const outputsAbsent=!fs.existsSync(negative.outputRoot);assert(result.code!==0&&outputsAbsent,'缺少口径时未失败或仍有输出');
const evidence={schema_version:1,task_asset_id:'postgres_checkout_experiment_revenue_review',result:'PASS',generated_at_utc:new Date().toISOString(),git_commit_sha:process.env.GITHUB_SHA,workflow_run_id:process.env.GITHUB_RUN_ID,runner:{os:process.env.RUNNER_OS,arch:process.env.RUNNER_ARCH,image_os:process.env.ImageOS,node:process.version,actual_windows_run:true},software:{postgresql_server_version_num:version.stdout.trim(),psql_path:psql},attachment_sha256:attachmentSha256,archive_checks:{input_members:[...inputMembers.keys()].sort(),reference_members:expectedReference,prohibited_platform_members:scan},workbook_checks:{answer_sheet_names:workbookSheets(path.join(artifactRoot,'关键标准答案.xlsx')),specification_sheet_names:workbookSheets(path.join(artifactRoot,'任务规格转化.xlsx'))},clean_runs:cleanRuns,crlf_case:{changed_input:'完成SQL行尾改为CRLF',exit_code:0,semantic_digest:crlfDigest,reference_match:true},positive_mutation:{changed_rule:'balance_watch_abs_delta_max从1改为0',exit_code:0,investigate_rows:2},invalid_input:{removed_input:'rules/analysis_policy.sql',exit_code:result.code,derived_outputs_absent:outputsAbsent},network:{formal_run_network_access:'仅Windows本机PostgreSQL17'}};
await fsp.writeFile(path.join(evidenceRoot,'windows-verification.json'),`${JSON.stringify(evidence,null,2)}\n`);console.log(JSON.stringify(evidence,null,2));
